# Generated by Django 3.1.2 on 2020-12-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vh_rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='description',
            field=models.TextField(help_text='Опишите, что означает значение рейтинга', verbose_name='Описание рейтинга'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='description_en',
            field=models.TextField(help_text='Опишите, что означает значение рейтинга', null=True, verbose_name='Описание рейтинга'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='description_ru',
            field=models.TextField(help_text='Опишите, что означает значение рейтинга', null=True, verbose_name='Описание рейтинга'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=4, help_text='Укажите значение от нуля до пяти с точночтью до десятых', max_digits=5, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='title',
            field=models.CharField(help_text='Укажите значение от нуля до пяти с точночтью до десятых', max_length=255, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='title_en',
            field=models.CharField(help_text='Укажите значение от нуля до пяти с точночтью до десятых', max_length=255, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='title_ru',
            field=models.CharField(help_text='Укажите значение от нуля до пяти с точночтью до десятых', max_length=255, null=True, verbose_name='Рейтинг'),
        ),
    ]
