# Generated by Django 3.1.8 on 2021-06-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vh_rating', '0002_auto_20201201_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='title',
            field=models.CharField(help_text='Укажите отображаемое наименование', max_length=255, verbose_name='Отображаемое наименование'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='title_en',
            field=models.CharField(help_text='Укажите отображаемое наименование', max_length=255, null=True, verbose_name='Отображаемое наименование'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='title_ru',
            field=models.CharField(help_text='Укажите отображаемое наименование', max_length=255, null=True, verbose_name='Отображаемое наименование'),
        ),
    ]
