# Generated by Django 3.1.8 on 2021-06-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vh_category', '0002_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_short_en',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_short_ru',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
