# Generated by Django 3.1.2 on 2020-10-18 00:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vh_rating', '__first__'),
        ('vh_medproc', '__first__'),
        ('vh_employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vh_employee.employee')),
                ('youtube', models.URLField(blank=True, help_text='Укажите ссылку на Youtube канал врача', max_length=250, null=True, verbose_name='Ссылка на Youtube')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
            bases=('vh_employee.employee',),
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Категория врача',
                'verbose_name_plural': 'Категории врачей',
            },
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
            },
        ),
        migrations.CreateModel(
            name='DoctorMedProc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(help_text='Укажите врача', on_delete=django.db.models.deletion.CASCADE, to='vh_doctor.doctor', verbose_name='Врач')),
                ('medproc', models.ForeignKey(help_text='Укажите процедуру, выполняемую выбранным врачом', on_delete=django.db.models.deletion.CASCADE, to='vh_medproc.medproc', verbose_name='Процедура')),
                ('rating', models.ForeignKey(blank=True, help_text='Укажите рейтинг процедуры, выполненную врачом', null=True, on_delete=django.db.models.deletion.CASCADE, to='vh_rating.rating', verbose_name='Рейтинг процедуры')),
            ],
            options={
                'verbose_name': 'Процедура врача',
                'verbose_name_plural': 'Процедуры врачей',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='level',
            field=models.ForeignKey(blank=True, help_text='Укажите категорию врача', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levelDoctors', to='vh_doctor.level', verbose_name='Категория врача'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='special',
            field=models.ForeignKey(blank=True, help_text='Укажите специализацию врача', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specDoctors', to='vh_doctor.special', verbose_name='Специализация врача'),
        ),
    ]
