# Generated by Django 3.1.2 on 2020-10-06 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vh_human', '0001_initial'),
        ('vh_doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='midName',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='title',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='usr',
        ),
        migrations.AddField(
            model_name='doctor',
            name='human_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vh_human.human'),
            preserve_default=False,
        ),
    ]
