# Generated by Django 3.1.2 on 2020-12-01 20:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vh_doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('code', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Ученая степень',
                'verbose_name_plural': 'Ученые степени',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='dt_practic',
            field=models.DateField(default=datetime.datetime(2017, 12, 1, 23, 40, 57, 13982), help_text='Укажите дату начала медецинской практики', verbose_name='Дата начала практики'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='education',
            field=models.TextField(blank=True, help_text='Укажите информацию об образовании врача', null=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='fb',
            field=models.URLField(blank=True, help_text='Укажите ссылку на Facebook канал врача', max_length=250, null=True, verbose_name='Ссылка на Facebook'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='insta',
            field=models.URLField(blank=True, help_text='Укажите ссылку на Instagram канал врача', max_length=250, null=True, verbose_name='Ссылка на Instagram'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='vk',
            field=models.URLField(blank=True, help_text='Укажите ссылку на ВКонтакте канал врача', max_length=250, null=True, verbose_name='Ссылка на ВКонтакте'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='сertificate',
            field=models.TextField(blank=True, help_text='Укажите информацию о сертификате врача', null=True, verbose_name='Сертификат'),
        ),
        migrations.AddField(
            model_name='level',
            name='code',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='special',
            name='code',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='degree',
            field=models.ForeignKey(blank=True, help_text='Укажите ученую степень если есть', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='degreeDoctors', to='vh_doctor.degree', verbose_name='Ученая степень'),
        ),
    ]
