# Generated by Django 3.1.2 on 2020-10-07 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vh_doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Врач', 'verbose_name_plural': 'Специальные поля Врача'},
        ),
    ]
