# Generated by Django 3.1.8 on 2021-06-03 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vh_doctor', '0004_auto_20210603_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='dt_practic',
            field=models.DateField(default=datetime.datetime(2018, 6, 4, 0, 2, 16, 771522), help_text='Укажите дату начала медецинской практики', verbose_name='Дата начала практики'),
        ),
    ]
