# Generated by Django 3.1.8 on 2021-06-03 22:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vh_doctor', '0005_auto_20210604_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='dt_practic',
            field=models.DateField(default=datetime.datetime(2018, 6, 4, 1, 6, 34, 810444), help_text='Укажите дату начала медецинской практики', verbose_name='Дата начала практики'),
        ),
        migrations.CreateModel(
            name='DocWorkRes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(help_text='Выбор изображения результата работы', upload_to='', verbose_name='Фото')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('pos', models.PositiveIntegerField(default=0, help_text='Укажите позицию связи для сортировки', verbose_name='Номер по порядку')),
                ('doctor', models.ForeignKey(help_text='Укажите врача', on_delete=django.db.models.deletion.CASCADE, to='vh_doctor.doctor', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Фото работы врача',
                'verbose_name_plural': 'Фото работ врачей',
            },
        ),
    ]
