# Generated by Django 3.1.12 on 2021-06-29 04:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vh_doctor', '0006_auto_20210604_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='education_en',
            field=models.TextField(blank=True, help_text='Укажите информацию об образовании врача', null=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='education_ru',
            field=models.TextField(blank=True, help_text='Укажите информацию об образовании врача', null=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='сertificate_en',
            field=models.TextField(blank=True, help_text='Укажите информацию о сертификате врача', null=True, verbose_name='Сертификат'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='сertificate_ru',
            field=models.TextField(blank=True, help_text='Укажите информацию о сертификате врача', null=True, verbose_name='Сертификат'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dt_practic',
            field=models.DateField(default=datetime.datetime(2018, 6, 29, 7, 48, 20, 198274), help_text='Укажите дату начала медецинской практики', verbose_name='Дата начала практики'),
        ),
        migrations.AlterField(
            model_name='doctormedproc',
            name='doctor',
            field=models.ForeignKey(help_text='Укажите врача', on_delete=django.db.models.deletion.CASCADE, related_name='medprocs', to='vh_doctor.doctor', verbose_name='Врач'),
        ),
    ]
