# Generated by Django 3.1.13 on 2021-08-08 20:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vh_category', '0003_auto_20210603_0034'),
        ('vh_doctor', '0007_auto_20210629_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='dt_practic',
            field=models.DateField(default=datetime.datetime(2018, 8, 8, 23, 14, 35, 694423), help_text='Укажите дату начала медецинской практики', verbose_name='Дата начала практики'),
        ),
        migrations.CreateModel(
            name='DocCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.PositiveIntegerField(default=0, help_text='Укажите позицию для сортировки', verbose_name='Номер по порядку')),
                ('category', models.ForeignKey(blank=True, help_text='Укажите специализацию врача из разделов каталога', null=True, on_delete=django.db.models.deletion.CASCADE, to='vh_category.category', verbose_name='Специализация')),
                ('doctor', models.ForeignKey(help_text='Укажите врача', on_delete=django.db.models.deletion.CASCADE, to='vh_doctor.doctor', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Связь врача со специализацией',
                'verbose_name_plural': 'Специализации врачей',
            },
        ),
    ]
