# Generated by Django 3.1.2 on 2020-10-18 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import vh_human.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('vh_rating', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('firstName', models.CharField(max_length=50)),
                ('firstName_ru', models.CharField(max_length=50, null=True)),
                ('firstName_en', models.CharField(max_length=50, null=True)),
                ('lastName', models.CharField(max_length=50)),
                ('lastName_ru', models.CharField(max_length=50, null=True)),
                ('lastName_en', models.CharField(max_length=50, null=True)),
                ('midName', models.CharField(blank=True, max_length=50, null=True)),
                ('midName_ru', models.CharField(blank=True, max_length=50, null=True)),
                ('midName_en', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=vh_human.models.image_upload_to)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_vh_human.human_set+', to='contenttypes.contenttype')),
                ('rating', models.ForeignKey(blank=True, help_text='Укажите рейтинг', null=True, on_delete=django.db.models.deletion.CASCADE, to='vh_rating.rating', verbose_name='Рейтинг')),
                ('usr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Персона',
                'verbose_name_plural': 'Персоны',
            },
        ),
    ]
