# Generated by Django 3.1.2 on 2020-10-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vh_human', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
