# Generated by Django 3.1.2 on 2020-10-07 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vh_human', '0002_auto_20201008_0049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='human',
            options={'verbose_name': 'Персона', 'verbose_name_plural': 'Персоны'},
        ),
    ]
