# Generated by Django 3.1.2 on 2020-11-30 20:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Укажите код обратной связи латинскими символами. CODE_CALL, CODE_FB', max_length=16, verbose_name='Код обратной связи')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Вид обратной связи',
                'verbose_name_plural': 'Виды обратной связи',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('call_hr', models.PositiveIntegerField(blank=True, null=True)),
                ('call_mn', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('fb_type', models.ForeignKey(help_text='Укажите вид обратной связи', on_delete=django.db.models.deletion.CASCADE, to='vh_feedback.feedbacktype', verbose_name='Вид обратной связи')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Журнал обратной связи и звонков',
            },
        ),
    ]
