# Generated by Django 3.1.2 on 2020-11-11 22:21

from django.db import migrations, models
import django.db.models.deletion
import rbkpay.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RBKEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iid', models.CharField(max_length=20)),
                ('dt', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('metatxt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RBKInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iid', models.CharField(max_length=20)),
                ('dt', models.DateTimeField(auto_now_add=True)),
                ('expire', models.DateTimeField(default=rbkpay.models.one_day_hence)),
                ('token', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=35, null=True)),
                ('descr', models.CharField(blank=True, max_length=255, null=True)),
                ('extra', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbkpay.rbkevent')),
            ],
        ),
    ]
