# Generated by Django 3.1.2 on 2020-10-31 21:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vh_medproc', '0001_initial'),
        ('vh_client', '0001_initial'),
        ('vh_doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('dt_start', models.DateTimeField(verbose_name='Дата и время процедуры')),
                ('comment', models.TextField(blank=True, null=True)),
                ('dt_create', models.DateTimeField(auto_now_add=True)),
                ('dt_update', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveIntegerField(default=0, verbose_name='Статус записи')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vh_client.client', verbose_name='Клиент')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vh_doctor.doctor', verbose_name='Врач')),
                ('medproc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vh_medproc.medproc', verbose_name='Процедура')),
            ],
            options={
                'verbose_name': 'Запись на приём',
                'verbose_name_plural': 'Записи на приём',
            },
        ),
    ]
