# Generated by Django 3.1.2 on 2020-11-12 22:23

from django.db import migrations, models
import django.db.models.deletion
import vh_booking.models


class Migration(migrations.Migration):

    dependencies = [
        ('vh_client', '0001_initial'),
        ('rbkpay', '0001_initial'),
        ('vh_booking', '0002_timeslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='dt_update',
        ),
        migrations.AddField(
            model_name='booking',
            name='dt_expire',
            field=models.DateTimeField(default=vh_booking.models.minutes_hence, verbose_name='Дата и время действия'),
        ),
        migrations.AddField(
            model_name='booking',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbkpay.rbkinvoice', verbose_name='Счет'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vh_client.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='unpaid', max_length=20, verbose_name='Статус записи'),
        ),
    ]
