# Generated by Django 3.1.2 on 2020-10-18 00:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vh_human', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Роль сотрудника',
                'verbose_name_plural': 'Роли сотрудников',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('human_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vh_human.human')),
                ('empNum', models.CharField(blank=True, max_length=20, null=True)),
                ('empRole', models.ForeignKey(blank=True, help_text='Укажите роль сотрудника в организации', null=True, on_delete=django.db.models.deletion.CASCADE, to='vh_employee.emprole', verbose_name='Роль сотрудника')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
            bases=('vh_human.human',),
        ),
    ]
