# Generated by Django 3.1.2 on 2021-03-05 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_short', models.CharField(max_length=35)),
                ('title_short_ru', models.CharField(max_length=35, null=True)),
                ('title_short_en', models.CharField(max_length=35, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='vh_dict.dictstring', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'Строка словаря',
                'verbose_name_plural': 'Строки словаря',
            },
        ),
    ]
