# Generated by Django 3.1.2 on 2020-10-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vh_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_check_en',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_check_ru',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
