# Generated by Django 3.1.2 on 2020-12-05 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vh_category', '0001_initial'),
        ('vh_product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.PositiveIntegerField(default=0, help_text='Укажите позицию связи для сортировки', verbose_name='Номер по порядку')),
                ('category', models.ForeignKey(blank=True, help_text='Укажите категорию из разделов каталога', null=True, on_delete=django.db.models.deletion.CASCADE, to='vh_category.category', verbose_name='Категория продукта')),
                ('product', models.ForeignKey(blank=True, help_text='Укажите продукт из каталога', null=True, on_delete=django.db.models.deletion.CASCADE, to='vh_product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Связь продукта с категорией',
                'verbose_name_plural': 'Категории продукта',
            },
        ),
    ]
