# Generated by Django 3.1.8 on 2021-06-03 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vh_human', '0001_initial'),
        ('vh_product', '0002_productcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHuman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.PositiveIntegerField(default=0, help_text='Укажите позицию связи для сортировки', verbose_name='Номер по порядку')),
                ('human', models.ForeignKey(blank=True, help_text='Веберите исполнителя продукта', null=True, on_delete=django.db.models.deletion.CASCADE, to='vh_human.human', verbose_name='Исполнитель')),
                ('product', models.ForeignKey(blank=True, help_text='Укажите продукт из каталога', null=True, on_delete=django.db.models.deletion.CASCADE, to='vh_product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Связь продукта с исполнителем',
                'verbose_name_plural': 'Исполнители продукта',
            },
        ),
    ]
