# Generated by Django 3.1.2 on 2020-10-07 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vh_product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedProc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vh_product.product')),
            ],
            options={
                'verbose_name': 'Процедура',
                'verbose_name_plural': 'Процедуры',
            },
        ),
    ]
