# Generated by Django 3.1.2 on 2020-10-18 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vh_product', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedProc',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vh_product.product')),
                ('duration', models.IntegerField(default=30)),
            ],
            options={
                'verbose_name': 'Процедура',
                'verbose_name_plural': 'Процедуры',
            },
            bases=('vh_product.product',),
        ),
    ]
