# Generated by Django 3.1.8 on 2021-06-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vh_medproc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medproc',
            name='recomend_after',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medproc',
            name='recomend_before',
            field=models.TextField(blank=True, null=True),
        ),
    ]
