# Generated by Django 3.1.8 on 2021-06-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vh_medproc', '0003_auto_20210604_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medproc',
            name='duration',
            field=models.IntegerField(default=30, help_text='Укажите продолжительность процедуры', verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='medproc',
            name='recomend_after',
            field=models.TextField(blank=True, help_text='Добавьте рекомендации после прохождения процедуры', null=True, verbose_name='После процедуры'),
        ),
        migrations.AlterField(
            model_name='medproc',
            name='recomend_after_en',
            field=models.TextField(blank=True, help_text='Добавьте рекомендации после прохождения процедуры', null=True, verbose_name='После процедуры'),
        ),
        migrations.AlterField(
            model_name='medproc',
            name='recomend_after_ru',
            field=models.TextField(blank=True, help_text='Добавьте рекомендации после прохождения процедуры', null=True, verbose_name='После процедуры'),
        ),
        migrations.AlterField(
            model_name='medproc',
            name='recomend_before',
            field=models.TextField(blank=True, help_text='Добавьте рекомендации для подготовке к прохождению процедуры', null=True, verbose_name='До процедуры'),
        ),
        migrations.AlterField(
            model_name='medproc',
            name='recomend_before_en',
            field=models.TextField(blank=True, help_text='Добавьте рекомендации для подготовке к прохождению процедуры', null=True, verbose_name='До процедуры'),
        ),
        migrations.AlterField(
            model_name='medproc',
            name='recomend_before_ru',
            field=models.TextField(blank=True, help_text='Добавьте рекомендации для подготовке к прохождению процедуры', null=True, verbose_name='До процедуры'),
        ),
    ]
